server:
  port: 7777

spring:
  application:
    name: config-server
  profiles:
    active: default

  cloud:
    config:
      server:
        git:
          uri: https://github.com/gibbssonfarias30/microservice-configs.git
          default-label: main
          clone-one-start: true
eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
